/*-----------------------------------------------------------
  File ......: hix_test_validator.prg
  Author.....: Charly 9000
  Created....: 2026-06-04
  Description: Integrated test — THixValidator v2 (2-hash API)
 -----------------------------------------------------------*/
#include "hbclass.ch"
#include "hix_lang.ch"

STATIC PROCEDURE _Ok( hCtx, lCond, cDesc )
   IF lCond ; HixTU_Pass( hCtx, cDesc ) ; ELSE ; HixTU_Fail( hCtx, cDesc, ".T.", ".F." ) ; ENDIF
RETURN

// Uses shared TMockRequest from hix_test_utils.prg

FUNCTION HIX_TestValidator_Run()
   LOCAL hCtx := { "total" => 0, "passed" => 0, "failed" => 0, "results" => {} }
   HIX_MetricsInit()
   HIX_LangSelect( "EN" )
   _ValSuiteA( hCtx )
   _ValSuiteB( hCtx )
   _ValSuiteC( hCtx )
   _ValSuiteD( hCtx )
   _ValSuiteE( hCtx )
   _ValSuiteF( hCtx )
   _ValSuiteG( hCtx )
   HIX_MetricsClose()
RETURN hCtx

STATIC PROCEDURE _ValSuiteA( hCtx )
   LOCAL oVal
   oVal := THixValidator():New( { "name" => "required" } )
   _Ok( hCtx, oVal:Make( { "name" => "Alice" } ), "A01 required passes non-empty string" )
   oVal := THixValidator():New( { "name" => "required" } )
   _Ok( hCtx, ! oVal:Make( { "name" => "" } ), "A02 required fails empty string" )
   oVal := THixValidator():New( { "qty" => "required" } )
   _Ok( hCtx, oVal:Make( { "qty" => 0 } ), "A03 required passes number 0" )
   oVal := THixValidator():New( { "active" => "required" } )
   _Ok( hCtx, oVal:Make( { "active" => .F. } ), "A04 required passes .F." )
   oVal := THixValidator():New( { "age" => "number" } )
   oVal:Make( { "age" => " 25 " } )
   _Ok( hCtx, oVal:Get("age") == 25, "A05 number cast from ' 25 '" )
   oVal := THixValidator():New( { "score" => "number|min:10" } )
   _Ok( hCtx, ! oVal:Make( { "score" => "5" } ), "A06 number|min:10 fails '5'" )
   oVal := THixValidator():New( { "flag" => "bool" } )
   oVal:Make( { "flag" => "on" } )
   _Ok( hCtx, oVal:Get("flag") == .T., "A07a bool cast from 'on'" )
   oVal := THixValidator():New( { "flag" => "bool" } )
   oVal:Make( { "flag" => "false" } )
   _Ok( hCtx, oVal:Get("flag") == .F., "A07b bool cast from 'false'" )
   oVal := THixValidator():New( { "flag" => "bool" } )
   oVal:Make( { "flag" => ".T." } )
   _Ok( hCtx, oVal:Get("flag") == .T., "A07c bool cast from '.T.' (Harbour rendered)" )
   oVal := THixValidator():New( { "flag" => "bool" } )
   oVal:Make( { "flag" => ".F." } )
   _Ok( hCtx, oVal:Get("flag") == .F., "A07d bool cast from '.F.' (Harbour rendered)" )
   oVal := THixValidator():New( { "dob" => "date" } )
   oVal:Make( { "dob" => "2024-12-31" } )
   _Ok( hCtx, ValType( oVal:Get("dob") ) == "D", "A08 date cast from '2024-12-31'" )
   oVal := THixValidator():New( { "price" => "min:10" } )
   _Ok( hCtx, ! oVal:Make( { "price" => 5 } ), "A09 min:10 fails number 5" )
   oVal := THixValidator():New( { "code" => "max:3" } )
   _Ok( hCtx, ! oVal:Make( { "code" => "ABCD" } ), "A10 max:3 fails string 'ABCD'" )
   oVal := THixValidator():New( { "email" => "ismail" } )
   _Ok( hCtx, oVal:Make( { "email" => "test@example.com" } ), "A11 ismail passes valid email" )
   oVal := THixValidator():New( { "email" => "ismail" } )
   _Ok( hCtx, ! oVal:Make( { "email" => "notanemail" } ), "A12 ismail fails invalid email" )
   oVal := THixValidator():New( { "amount" => "decimal" } )
   oVal:Make( { "amount" => "1250.50" } )
   _Ok( hCtx, ValType( oVal:Get("amount") ) == "N", "A13 decimal cast '1250.50'" )
   oVal := THixValidator():New( { "usr" => { "required", "Username", "" } } )
   oVal:Make( { "usr" => "" } )
   _Ok( hCtx, "Username" $ oVal:GetFirstError(), "A14 array form label in error" )
   oVal := THixValidator():New( { "lang" => { "required", "Language", "en" } } )
   oVal:Make( { => } )
   _Ok( hCtx, oVal:Get("lang") == "en", "A15 array form default fills missing field" )
   oVal := THixValidator():New( { "age" => {|v| iif( v >= 18, NIL, "Must be 18+" ) } } )
   oVal:Make( { "age" => 16 } )
   _Ok( hCtx, oVal:GetFirstError() == "Must be 18+", "A16 codeblock returns custom message" )
   oVal := THixValidator():New( { "x" => {|v| v > 0 } } )
   _Ok( hCtx, ! oVal:Make( { "x" => -1 } ), "A17 codeblock returning .F. gives error" )
   oVal := THixValidator():New( { "tag" => "required" }, { "tag" => "upper" } )
   oVal:Make( { "tag" => "hello" } )
   _Ok( hCtx, oVal:Get("tag") == "HELLO", "A18 sanitizer upper applied via hSanitate" )
RETURN

STATIC PROCEDURE _ValSuiteB( hCtx )
   LOCAL oVal, hInput
   oVal := THixValidator():New( { "note" => "optional|min:2" } )
   _Ok( hCtx, oVal:Make( { => } ), "B01 optional absent no error" )
   oVal := THixValidator():New( { "note" => "optional|min:5" } )
   _Ok( hCtx, ! oVal:Make( { "note" => "Hi" } ), "B02 optional present validates rest" )
   oVal := THixValidator():New( { "n" => "between:1,10" } )
   _Ok( hCtx, oVal:Make( { "n" => 5 } ), "B03 between:1,10 passes 5" )
   oVal := THixValidator():New( { "n" => "between:1,10" } )
   _Ok( hCtx, ! oVal:Make( { "n" => 0 } ), "B04 between:1,10 fails 0" )
   oVal := THixValidator():New( { "code" => "between:3,8" } )
   _Ok( hCtx, oVal:Make( { "code" => "abcde" } ), "B05 between:3,8 passes string len 5" )
   oVal := THixValidator():New( { "id" => "integer" } )
   _Ok( hCtx, oVal:Make( { "id" => 42 } ), "B06a integer passes 42" )
   oVal := THixValidator():New( { "id" => "integer" } )
   _Ok( hCtx, ! oVal:Make( { "id" => 42.5 } ), "B06b integer fails 42.5" )
   oVal := THixValidator():New( { "qty" => "positive" } )
   _Ok( hCtx, oVal:Make( { "qty" => 1 } ), "B07a positive passes 1" )
   oVal := THixValidator():New( { "qty" => "positive" } )
   _Ok( hCtx, ! oVal:Make( { "qty" => 0 } ), "B07b positive fails 0" )
   oVal := THixValidator():New( { "qty" => "positive" } )
   _Ok( hCtx, ! oVal:Make( { "qty" => -1 } ), "B07c positive fails -1" )
   oVal := THixValidator():New( { "lang" => "in:es,en,fr" } )
   _Ok( hCtx, oVal:Make( { "lang" => "en" } ), "B08a in:es,en,fr passes 'en'" )
   oVal := THixValidator():New( { "lang" => "in:es,en,fr" } )
   _Ok( hCtx, ! oVal:Make( { "lang" => "de" } ), "B08b in:es,en,fr fails 'de'" )
   oVal := THixValidator():New( { "user" => "notin:admin,root" } )
   _Ok( hCtx, ! oVal:Make( { "user" => "admin" } ), "B09a notin fails 'admin'" )
   oVal := THixValidator():New( { "user" => "notin:admin,root" } )
   _Ok( hCtx, oVal:Make( { "user" => "carles" } ), "B09b notin passes 'carles'" )
   oVal := THixValidator():New( { "code" => "regex:^[A-Z]{3}$" } )
   _Ok( hCtx, oVal:Make( { "code" => "ABC" } ), "B10a regex passes 'ABC'" )
   oVal := THixValidator():New( { "code" => "regex:^[A-Z]{3}$" } )
   _Ok( hCtx, ! oVal:Make( { "code" => "ab1" } ), "B10b regex fails 'ab1'" )
   oVal := THixValidator():New( { "site" => "isurl" } )
   _Ok( hCtx, oVal:Make( { "site" => "https://example.com" } ), "B11a isurl passes" )
   oVal := THixValidator():New( { "site" => "isurl" } )
   _Ok( hCtx, ! oVal:Make( { "site" => "no-url" } ), "B11b isurl fails 'no-url'" )
   oVal := THixValidator():New( { "addr" => "isip" } )
   _Ok( hCtx, oVal:Make( { "addr" => "192.168.1.1" } ), "B12a isip passes '192.168.1.1'" )
   oVal := THixValidator():New( { "addr" => "isip" } )
   _Ok( hCtx, ! oVal:Make( { "addr" => "999.1.2.3" } ), "B12b isip fails '999.1.2.3'" )
   hInput := { "pass" => "secret", "pass_confirmation" => "secret" }
   oVal := THixValidator():New( { "pass" => "confirmed" } )
   _Ok( hCtx, oVal:Make( hInput ), "B13 confirmed passes when match" )
   hInput := { "pass" => "secret", "pass_confirmation" => "other" }
   oVal := THixValidator():New( { "pass" => "confirmed" } )
   _Ok( hCtx, ! oVal:Make( hInput ), "B14 confirmed fails when differ" )
   oVal := THixValidator():New( { "d" => "mindate:2020-01-01" } )
   _Ok( hCtx, oVal:Make( { "d" => "2021-06-15" } ), "B15 mindate passes later date" )
   oVal := THixValidator():New( { "d" => "maxdate:2020-01-01" } )
   _Ok( hCtx, ! oVal:Make( { "d" => "2021-06-15" } ), "B16 maxdate fails later date" )
RETURN

STATIC PROCEDURE _ValSuiteC( hCtx )
   LOCAL oVal
   oVal := THixValidator():New( { => }, { "s" => "trim" } )
   oVal:Make( { "s" => "  hello  " } )
   _Ok( hCtx, oVal:Get("s") == "hello", "C01 trim removes spaces" )
   oVal := THixValidator():New( { => }, { "s" => "ltrim" } )
   oVal:Make( { "s" => "  hello  " } )
   _Ok( hCtx, Left( oVal:Get("s"), 1 ) == "h" .AND. Right( oVal:Get("s"), 2 ) == "  ", "C02 ltrim left only" )
   oVal := THixValidator():New( { => }, { "s" => "rtrim" } )
   oVal:Make( { "s" => "  hello  " } )
   _Ok( hCtx, Left( oVal:Get("s"), 2 ) == "  " .AND. Right( oVal:Get("s"), 1 ) == "o", "C03 rtrim right only" )
   oVal := THixValidator():New( { => }, { "s" => "strip_tags" } )
   oVal:Make( { "s" => "<b>bold</b>" } )
   _Ok( hCtx, oVal:Get("s") == "bold", "C04 strip_tags removes HTML" )
   oVal := THixValidator():New( { => }, { "s" => "slug" } )
   oVal:Make( { "s" => "Hello World!" } )
   _Ok( hCtx, oVal:Get("s") == "hello-world", "C05 slug 'Hello World!'" )
   oVal := THixValidator():New( { => }, { "n" => "round:2" } )
   oVal:Make( { "n" => 3.14159 } )
   _Ok( hCtx, oVal:Get("n") == 3.14, "C06 round:2 gives 3.14" )
   oVal := THixValidator():New( { => }, { "n" => "abs" } )
   oVal:Make( { "n" => -5 } )
   _Ok( hCtx, oVal:Get("n") == 5, "C07 abs converts -5 to 5" )
   oVal := THixValidator():New( { => }, { "s" => "nl2br" } )
   oVal:Make( { "s" => "line1" + Chr(10) + "line2" } )
   _Ok( hCtx, "<br>" $ oVal:Get("s"), "C08 nl2br inserts <br>" )
   oVal := THixValidator():New( { => }, { "s" => "lower|trim" } )
   oVal:Make( { "s" => "  HELLO  " } )
   _Ok( hCtx, oVal:Get("s") == "hello", "C09 lower|trim in sequence" )
   oVal := THixValidator():New( { "s" => "required" }, { "s" => "upper" } )
   oVal:Make( { "s" => "" } )
   _Ok( hCtx, oVal:Fails() .AND. oVal:Get("s") == "", "C10 sanitize skipped when fails" )
RETURN

STATIC PROCEDURE _ValSuiteD( hCtx )
   LOCAL oVal, hErr, cJson, hParsed, cTxt
   HIX_LangSelect( "ES" )
   oVal := THixValidator():New( { "nombre" => "required" } )
   oVal:Make( { "nombre" => "" } )
   _Ok( hCtx, "El campo" $ oVal:GetFirstError(), "D01 ES required message in Spanish" )
   HIX_LangSelect( "EN" )
   oVal := THixValidator():New( { "nombre" => "required" } )
   oVal:Make( { "nombre" => "" } )
   _Ok( hCtx, "The field" $ oVal:GetFirstError(), "D02 EN required message in English" )
   oVal := THixValidator():New( { "code" => "min:5" } )
   oVal:Make( { "code" => "ab" } )
   _Ok( hCtx, "5" $ oVal:GetFirstError(), "D03 min:5 includes '5'" )
   oVal := THixValidator():New( { "a" => "required", "b" => "required" } )
   oVal:Make( { "a" => "", "b" => "" } )
   _Ok( hCtx, ! Empty( oVal:GetFirstError() ), "D04 GetFirstError non-empty" )
   oVal := THixValidator():New( { "x" => "required" } )
   oVal:Make( { "x" => "ok" } )
   _Ok( hCtx, oVal:GetFirstError() == "", "D05 GetFirstError empty when Passes()" )
   oVal := THixValidator():New( { "f" => "required" } )
   oVal:Make( { "f" => "" } )
   cJson := oVal:GetErrorsJson()
   hParsed := NIL
   hb_jsonDecode( cJson, @hParsed )
   _Ok( hCtx, ValType( hParsed ) == "H", "D06 GetErrorsJson returns parseable JSON" )
   oVal := THixValidator():New( { "f" => "required" } )
   oVal:Make( { "f" => "" } )
   cTxt := oVal:GetErrorsTxt()
   _Ok( hCtx, ! ( "<table" $ cTxt ) .AND. "f:" $ cTxt, "D07 GetErrorsTxt plain text no HTML" )
   oVal := THixValidator():New( { "f" => "required" } )
   oVal:Make( { "f" => "" } )
   cTxt := oVal:GetErrorsHtml()
   _Ok( hCtx, "<table" $ cTxt, "D07b GetErrorsHtml contains <table>" )
   oVal := THixValidator():New( { "x" => "required" } )
   oVal:Make( { "x" => "" } )
   hErr := oVal:GetErrors()
   _Ok( hCtx, ValType( hErr ) == "H" .AND. hb_HHasKey( hErr, "x" ), "D08 GetErrors hash field=>msg" )
RETURN

STATIC PROCEDURE _ValSuiteE( hCtx )
   LOCAL oReq, oVal
   oReq := TMockRequest():New()
   oReq:hFormBody := { "name" => "Alice" }
   HIX_SetRequest( oReq )
   oVal := UValidatePost( { "name" => "required" } )
   _Ok( hCtx, oVal:Make(), "E01 UValidatePost reads FormBody" )
   oReq := TMockRequest():New()
   oReq:hFormBody := { => }
   HIX_SetRequest( oReq )
   oVal := UValidatePost( { "name" => "required" } )
   _Ok( hCtx, ! oVal:Make(), "E02 UValidatePost fails when field missing" )
   oReq := TMockRequest():New()
   oReq:hQueryParams := { "page" => "1" }
   HIX_SetRequest( oReq )
   oVal := UValidateGet( { "page" => "required" } )
   _Ok( hCtx, oVal:Make(), "E03 UValidateGet reads query params" )
   oReq := TMockRequest():New()
   oReq:xJsonBody := { "token" => "abc123" }
   HIX_SetRequest( oReq )
   oVal := UValidateJson( { "token" => "required" } )
   _Ok( hCtx, oVal:Make(), "E04 UValidateJson reads JSON body" )
   oReq := TMockRequest():New()
   oReq:hFormBody := { "qty" => "5" }
   HIX_SetRequest( oReq )
   oVal := UValidatePost( { "qty" => "required|number" } )
   oVal:Make()
   _Ok( hCtx, oVal:Get("qty") == 5, "E05 UValidatePost FormBody qty=5" )
   oReq := TMockRequest():New()
   oReq:hFormBody := { => }
   HIX_SetRequest( oReq )
   oVal := UValidateOrFail( { "name" => "required" } )
   _Ok( hCtx, oVal == NIL, "E06 UValidateOrFail returns NIL on failure" )
   _Ok( hCtx, oReq:nStatus == 422, "E06b UValidateOrFail sends 422" )
   oReq := TMockRequest():New()
   HIX_SetRequest( oReq )
   oVal := THixValidator():New( { "f" => "required" }, NIL, oReq )
   oVal:Make( { "f" => "" } )
   oVal:SendErrors( 422 )
   _Ok( hCtx, oReq:nStatus == 422 .AND. oReq:lResponded, "E07 SendErrors sends 422" )
   oReq := TMockRequest():New()
   HIX_SetRequest( oReq )
   oVal := THixValidator():New( { "f" => "required" }, NIL, oReq )
   oVal:Make( { "f" => "" } )
   oVal:SendErrors( 400 )
   _Ok( hCtx, oReq:nStatus == 400, "E08 SendErrors(400) sends 400" )
RETURN

STATIC PROCEDURE _ValSuiteF( hCtx )
   LOCAL oVal, hDF, hSub
   oVal := THixValidator():New( { "id" => "required|number|field", "name" => "required" } )
   oVal:Make( { "id" => "42", "name" => "Alice" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, ValType( hDF ) == "H" .AND. hb_HHasKey( hDF, "id" ) .AND. hDF["id"] == 42, ;
        "F01 DataFields populated with cast value" )
   oVal := THixValidator():New( { "id" => "required|number|field", "name" => "required" } )
   oVal:Make( { "id" => "42", "name" => "" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, oVal:Fails() .AND. Len( hDF ) == 0, "F02 DataFields empty when fails" )
   oVal := THixValidator():New( { "html" => "required|escapedfield" } )
   oVal:Make( { "html" => "<script>" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, hb_HHasKey( hDF, "html" ) .AND. "&lt;" $ hDF["html"], "F03 escapedfield HTML-encodes" )
   oVal := THixValidator():New( { "name" => "required|field" }, { "name" => "lower" } )
   oVal:Make( { "name" => "ALICE" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, hb_HHasKey( hDF, "name" ) .AND. hDF["name"] == "alice", "F04 DataFields sanitized" )
   oVal := THixValidator():New( { "tag" => "field" } )
   oVal:Make( { "tag" => "harbour" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, hb_HHasKey( hDF, "tag" ) .AND. hDF["tag"] == "harbour", "F05 field-only populates DataFields" )
   oVal := THixValidator():New( { "tag" => "required|field" } )
   oVal:Make( { "tag" => "" } )
   hDF := oVal:DataFields()
   _Ok( hCtx, oVal:Fails() .AND. Len( hDF ) == 0, "F06 required|field fails -> DataFields empty" )
   oVal := THixValidator():New( { "a" => "required", "b" => "required", "c" => "required" } )
   oVal:Make( { "a" => "1", "b" => "2", "c" => "3" } )
   hSub := oVal:Validated( { "a", "c" } )
   _Ok( hCtx, hb_HHasKey( hSub, "a" ) .AND. hb_HHasKey( hSub, "c" ) .AND. ;
        ! hb_HHasKey( hSub, "b" ), "F07 Validated(aFields) returns subset" )
   oVal := THixValidator():New( { "age" => "number|min:18" } )
   _Ok( hCtx, ! oVal:MakeParameter( "age", "16" ), "F08 MakeParameter fails age<18" )
RETURN

STATIC PROCEDURE _ValSuiteG( hCtx )
   LOCAL oVal, hR

   oVal := UValidatorOne( "age", "25", "required|number|resume" )
   hR   := oVal:Resume()
   _Ok( hCtx, oVal:Passes() .AND. hR["age"] == 25, "G01 resume hash: cast number" )

   oVal := UValidatorOne( "active", "on", "required|bool|resume" )
   hR   := oVal:Resume()
   _Ok( hCtx, oVal:Passes() .AND. hR["active"] == .T., "G02 resume hash: cast bool .T." )

   oVal := UValidatorOne( "active", "false", "required|bool|resume" )
   hR   := oVal:Resume()
   _Ok( hCtx, oVal:Passes() .AND. hR["active"] == .F., "G03 resume hash: cast bool .F." )

   oVal := UValidatorOne( "name", "", "required|resume" )
   _Ok( hCtx, oVal:Fails() .AND. ValType( oVal:Resume() ) == "H", "G04 resume hash even when fails" )

   oVal := UValidatorOne( "age", "25", "required|number" )
   _Ok( hCtx, ValType( oVal:Resume() ) == "H", "G05 no resume returns input hash" )

   oVal := THixValidator():New( { "age" => "required|number|resume", "score" => "required|number|resume" } )
   oVal:Make( { "age" => "30", "score" => "9.5" } )
   hR := oVal:Resume()
   _Ok( hCtx, ValType( hR ) == "H" .AND. hR["age"] == 30 .AND. hR["score"] == 9.5, "G06 multi-resume hash" )

   oVal := THixValidator():New( { "name" => "required|resume" }, { "name" => "upper" } )
   oVal:Make( { "name" => "alice" } )
   hR := oVal:Resume()
   _Ok( hCtx, hR["name"] == "ALICE", "G07 resume hash: post-sanitize value" )

RETURN
